#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# This script migrates data and users from ownCloud to Nextcloud
#

mysql -e "select * from owncloud.users" &> /dev/null
if [ $? -gt 0 ]; then # no migration needed
    exit 0
fi

su - apache -s /bin/bash -c "source /opt/rh/rh-php71/enable; cd /usr/share/nextcloud/; php occ maintenance:mode --on"

for user_simple in `mysql owncloud -B -e "select uid from users;"`
do
    dir="/var/www/html/owncloud/data/$user_simple"
    if [ -d $dir ]; then
        echo "Nextcloud: migrating built-in user: $user_simple"
        /bin/su  apache -s /bin/bash -c "OC_PASS=Nethesis,1234 /var/www/html/nextcloud/occ user:add -n --password-from-env $user_simple"
        mv $dir /var/lib/nethserver/nextcloud/$user_simple
    fi 
done

for user_ldap in `mysql owncloud -N -B -e "select owncloud_name from ldap_user_mapping"`
do
    dn=$(mysql owncloud -N -B -e "select ldap_dn from ldap_user_mapping where owncloud_name='$user_ldap'")
    dst=$(mysql nextcloud -N -B -e "select owncloud_name from oc_ldap_user_mapping where (ldap_dn like 'cn=$user_ldap,%' or ldap_dn like 'uid=$user_ldap,%')")
    dir="/var/www/html/owncloud/data/$user_ldap"
    dst_dir="/var/lib/nethserver/nextcloud/$dst"
    if [ -d $dir ]; then
        if [[ -d $dst_dir ]]; then
            echo "[WARNING] Destination already exists for $user_ldap: existing directory renamed to ${dst_dir}.old"
            mv $dst_dir "$dst_dir".old
        fi
        echo "[NOTICE] Nextcloud: migrating LDAP user: $user_ldap"
        mv $dir $dst_dir
        chown -R apache:apache $dst_dir
    fi
done

su - apache -s /bin/bash -c "source /opt/rh/rh-php71/enable; cd /usr/share/nextcloud/; php occ files:scan --all"
su - apache -s /bin/bash -c "source /opt/rh/rh-php71/enable; cd /usr/share/nextcloud/; php occ maintenance:mode --off"
